dealers/carsifydealers/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('login/',views.user_login,name="userlogin"),
    path('signup/',views.signup,name="usersignup"),
    path('logout/',views.user_logout,name="userlogout"),
    path('addcar/',views.Addcar,name="addcar"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),

]

dealers/dealers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('carsifydealers.urls'))
]

dealers/carsifydealers/models.py
from turtle import update
from django.db import models
from django.contrib.auth.models import User
import os
from django.conf import settings


class Gumasta(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    gumsata=models.FileField(upload_to='media/dealerApplications/')

class India_States(models.Model):
    State_Name = models.TextField(null=True)
    def __str__(self):
        return self.State_Name

class Contact(models.Model):
    Name = models.TextField(null=True)
    Phone = models.IntegerField(null=True)
    City = models.TextField(null=True)
    State = models.TextField(null=True)
    Query = models.TextField(null=True)
    Remark = models.TextField(null=True)

    def __int__(self):
        return self.Phone

class Newsletter(models.Model):
    Email = models.EmailField(null=True)

    def __str__(self):
        return self.Email

class Address_Type(models.Model):
    Type = models.TextField(null=True)

    def __str__(self):
        return self.Type

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Address_Typee = models.ForeignKey(Address_Type, on_delete=models.CASCADE, null=True)
    street_address = models.CharField(max_length=100, null=True)
    apartment_address = models.CharField(max_length=100, null=True)
    City = models.TextField(null=True)
    State = models.TextField(null=True)
    country = models.TextField(null=True)
    zip = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username + ' -- ' + self.Address_Typee.Type

class UserProfile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    ProfileImg = models.FileField(null=True)
    ContactNo = models.IntegerField(null=True)
    Email = models.EmailField(null=True)
    Address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True)
    isDealer = models.BooleanField(default="False")
    #Documents
    AddharNumber = models.IntegerField(null=True, default=0000000000000000)
    PanNumber = models.TextField(null=True)
    VoterID = models.TextField(null=True)

    def __str__(self):
        return self.user.username

#all about cars from here

class Car_Company(models.Model):
    Car_Company_Name = models.TextField(null=True)
    def __str__(self):
        return self.Car_Company_Name

class Car_Fuel(models.Model):
    Car_Fuel_Type = models.TextField(null=True)
    def __str__(self):
        return self.Car_Fuel_Type

class Transmission_Type(models.Model):
    Tranmission = models.TextField(null=True)
    def __str__(self):
        return self.Tranmission


class Car_Model(models.Model):
    Company_Name = models.ForeignKey(Car_Company,on_delete=models.CASCADE,null=True)
    Car_Model_Name = models.TextField(null=True)

    def __str__(self):
        return self.Company_Name.Car_Company_Name +' -- '+ self.Car_Model_Name


class Number_of_Owners(models.Model):
    Owners = models.IntegerField(null=True)
    Postfix = models.TextField(null=True)

    def __str__(self):
        return self.Postfix

class Car_Body_Type(models.Model):
    body_type = models.TextField(null=True)

    def __str__(self):
        return self.body_type

class Individual_Car_Details(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    Company = models.ForeignKey(Car_Company,on_delete=models.CASCADE,null=True)
    Model = models.ForeignKey(Car_Model,on_delete=models.CASCADE,null=True)
    Registration_State = models.ForeignKey(India_States, on_delete=models.CASCADE, null=True)
    City = models.TextField(null=True)
    Fuel_Type = models.ForeignKey(Car_Fuel, on_delete=models.CASCADE, null=True)
    Transmission = models.ForeignKey(Transmission_Type, on_delete=models.CASCADE, null=True)
    Owners = models.ForeignKey(Number_of_Owners,on_delete=models.CASCADE,null=True)
    Body_Type = models.ForeignKey(Car_Body_Type,on_delete=models.CASCADE,null=True)
    Car_Status = models.BooleanField(default=False)

    Date_of_Manufacturing = models.DateField(null=True)
    Card_Registration_Number = models.TextField(null=True)
    Car_Varient = models.TextField(null=True)
    KM = models.IntegerField(null=True)
    Showimage = models.ImageField(null=False, blank=False)
    Color = models.TextField(null=True)
    Price = models.IntegerField(null=True)
    Insurance = models.TextField(null=True)
    Insurance_Type = models.TextField(null=True)
    Discription = models.TextField(null=True)

    showB2C = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username+' -- '+ self.Card_Registration_Number

class Individual_Car_Images(models.Model):
    carid = models.ForeignKey(Individual_Car_Details,on_delete=models.CASCADE,null=True)
    Image = models.ImageField(null=False, blank=False)

    def __str__(self):
        return self.carid.user.username +' -- '+ self.carid.Card_Registration_Number


#user Favourites cars
class UserFavouriteCars(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    carid = models.ForeignKey(Individual_Car_Details,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.user.username+' -- '+ self.carid.Card_Registration_Number

# Dealer's Models
class DealerApplication(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    Name = models.CharField(max_length = 100)
    Email = models.EmailField()
    Contact = models.CharField(max_length = 12)
    Document = models.FileField(upload_to= 'media/dealerApplications/')

class Dealer(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    location = models.CharField(max_length = 100)
    Company_Name = models.CharField(max_length = 100)
    Contact = models.CharField(max_length = 12)
    Email = models.EmailField()
    Document = models.FileField(upload_to= 'media/dealers/')
    

dealers/carsifydealers/forms.py
from dataclasses import field
from distutils.command.upload import upload
from email.policy import default
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
# from.models import Post


class SignUpForm(UserCreationForm):
	password1= forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password2= forms.CharField(label='Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
	phonenumber=forms.CharField(label="Mobile")
	gumasta=forms.FileField(label='Gumasta')
	# name=forms.TextInput()
	class Meta(UserCreationForm.Meta):
		model = User
		fields=UserCreationForm.Meta.fields+('username',"phonenumber","first_name",'gumasta')
		label={'phonenumber':"Mobile","first_name":"Name",'gumasta':"Gumasta"}
		widgets ={'username': forms.TextInput(attrs={'class':'form-control'}),
		# 'name': forms.TextInput(attrs={'class':'form-control'}),
		'first_name': forms.TextInput(attrs={'class':'form-control','required':True,}),
		# 'last_name': forms.TextInput(attrs={'class':'form-control','required':True,}),
		# 'email': forms.EmailInput(attrs={'class':'form-control','required':True,}),
		'phonenumber':forms.CharField(attrs={'class':'form-control','required'=True,}),
		'gumasta':forms.ImageField(),
		}

class LoginForm(AuthenticationForm):
	username=UsernameField(label='UserName',widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
	password=forms.CharField(label=_('Password'),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

dealers/carsifydealers/views.py
import email
from django.db.models.base import Model
from django.db.models.query import RawQuerySet
from django.shortcuts import render, redirect,HttpResponseRedirect,HttpResponse
from django.views.decorators import csrf
from .models import *
from django.contrib.auth.models import User
# from django.contrib.auth import 
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.auth import login, logout, authenticate
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.db.models import Min,Max,Q
from django.views.decorators.csrf import csrf_exempt
import datetime
from django.core.mail import EmailMultiAlternatives
import cv2
import numpy as np
from zipfile import ZipFile
import os
from os.path import basename
from wsgiref.util import FileWrapper
import random
from django.core.paginator import Paginator
from django.contrib.auth.hashers import check_password
from django.forms import forms
from .forms import SignUpForm, LoginForm
from django.contrib import messages
def home(request):
	return render(request, 'carsifydealers/home.html')


def user_login(request):
	if not request.user.is_authenticated:
		if request.method=="POST":
			form= LoginForm(request=request,data=request.POST)
			if form.is_valid():
				uname=form.cleaned_data['username']
				upass=form.cleaned_data['password']
				user=authenticate(username=uname,password=upass)
				if user is not None and user.is_active:
					login(request,user)
					messages.success(request,"Login Successfull !!!")
					return HttpResponseRedirect('/')
		else:
			form=LoginForm()
		return render(request,'carsifydealers/login2.html',{'form':form})
	else:
		return HttpResponseRedirect('/')

	
	

# Signup
def signup(request):
	if request.method=='POST':
		print("posst")
		form=SignUpForm(request.POST)
		print(form)
		# print(request.post.get['gumasta'])
		if form.is_valid():
			print(form)
			user=form.save()
			user.is_active=False
			messages.success(request,"you will get your account registered soon")
			form.save()
	else:
		form=SignUpForm()
	return render(request,'carsifydealers/signup.html',{'form':form})

# Logout
def user_logout(request):
	logout(request)
	messages.success(request,'Logout Successfull')
	return HttpResponseRedirect('/')

def about(request):
	return render(request, 'carsifydealers/about.html')

def contact(request):
	return render(request, 'carsifydealers/contact.html')


def Addcar(request):
    car_company = Car_Company.objects.all()
    car_model = Car_Model.objects.all()
    registeredstate = India_States.objects.all()
    numberofowners = Number_of_Owners.objects.all()
    vehicletype = Car_Body_Type.objects.all()
    tansmission = Transmission_Type.objects.all()
    fueltype = Car_Fuel.objects.all()
    print(car_company)


    if request.method == "POST":
        x = request.POST
        companyname = x['companyname']
        companyobj = Car_Company.objects.get(id=companyname)
        modelidd = x['modelname']
        modelname = Car_Model.objects.get(id=modelidd)
        VehicleNumber = x['VehicleNumber']
        Varient = x['Varient']
        RegisteredStateidd = x['RegisteredState']
        RegisteredState = India_States.objects.get(id=RegisteredStateidd)
        Registeredcity = x['Registeredcity']
        NumberofOwnersidd = x['NumberofOwners']
        NumberofOwners = Number_of_Owners.objects.get(id=NumberofOwnersidd)
        Manufacturing = x['Manufacturing']
        DManufacturing = datetime.date(int(Manufacturing), 1, 1)
        VehicalTypeidd = x['VehicalType']
        VehicalType = Car_Body_Type.objects.get(id=VehicalTypeidd)
        Transmissionidd = x['Transmission']
        Transmission = Transmission_Type.objects.get(id=Transmissionidd)
        Km = x['Km']
        color = x['color']
        FuelTypeidd = x['FuelType']
        FuelType = Car_Fuel.objects.get(id=FuelTypeidd)
        Price = x['Price']
        Insurance = x['Insurance']
        InsuranceType = x['InsuranceType']
        Comment = x['Comment']

        Images = request.FILES.getlist('Images')
        showimage = Images[0]

        #create a vehicle object here
        cid = Individual_Car_Details.objects.create(user=request.user, Company=companyobj, Model=modelname,\
            Registration_State=RegisteredState, Fuel_Type =FuelType, Transmission=Transmission, Owners=NumberofOwners,\
            Body_Type=VehicalType, Date_of_Manufacturing = DManufacturing, Card_Registration_Number=VehicleNumber,\
            Car_Varient=Varient, KM=Km, Color=color, Price=Price, Insurance=Insurance, Insurance_Type=InsuranceType, \
            City=Registeredcity, Discription=Comment, Showimage=showimage)

        #show image handeled
        '''
        imm = cid.Showimage
        img_path = imm.path
        img_name = str(imm)
        new_img = resize_img_show(img_path, img_name)
        cid.Showimage = new_img
        cid.save()
        os.remove(img_path)
        '''

        #creating image objects
        for image in Images:
            photo = Individual_Car_Images.objects.create(carid=cid, Image=image)
            '''
            imm = photo.Image

            img_path = imm.path
            img_name = str(imm)

            new_img = resize_img(img_path, img_name)
            photo.Image = new_img
            photo.save()
            os.remove(img_path)
            '''


        #return success page
        return HttpResponseRedirect('/')



    dic = {'car_company':car_company, 'car_model':car_model, 'registeredstate':registeredstate,\
            'numberofowners': numberofowners, 'vehicletype': vehicletype, 'tansmission':tansmission,\
           'fueltype':fueltype}

    return render(request, 'carsifydealers/addcar.html', dic)

def json_Car_add(request):
    car_company = list(Car_Company.objects.values())

    return JsonResponse({'data':car_company})

def json_Car_model(request, *args, **kwarg):
    selecedted_car = kwarg.get('car')
    obj_models = list(Car_Model.objects.filter(Company_Name=selecedted_car).values())

    return JsonResponse({'data':obj_models})

dealers/carsifydealers/templates/carsifydealers/about.html
{% extends 'carsifydealers/base.html' %}
{% load static %}
{% block title %}MyBlog|About{% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">About Page </h3>
    <p>Abdul Rashid Salim Salman Khan (Hindi: [səlˈmɑːn xɑːn]; 27 December 1965)[2] is an Indian actor, film producer, and television personality who works in Hindi films. In a film career spanning over thirty years, Khan has received numerous awards, including two National Film Awards as a film producer, and two Filmfare Awards for acting.[3] He is cited in the media as one of the most commercially successful actors of Indian cinema.[4][5] Forbes included him in their 2015 list of Top-Paid 100 Celebrity Entertainers in the world; Khan tied with Amitabh Bachchan for No. 71 on the list, both with earnings of $33.5 million.[6][7] According to the Forbes 2018 list of Top-Paid 100 Celebrity Entertainers in world, Khan was the highest-ranked Indian with 82nd rank with earnings of $37.7 million.[8][9] He is also known as the host of the reality show, Bigg Boss since 2010.</p>
</div>
{% endblock content %}

dealers/carsifydealers/templates/carsifydealers/addpost.html
{% extends 'carsifydealers/base.html' %}
{% load static %}
{% block title %}MyBlog|AddPost{% endblock title %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Add Posts</h3>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
            <h3>{{fm.label_tag}}</h3>{{fm}}
            <span class="errorlist text-warning">{{fm.errors|striptags}}</span><br><br>
        </div>
        {% endfor %}
        <input type="submit" value="Add" class="btn btn-outline-success btn-lg mx-2">
        <a href="{% url 'dashboard' %}" class="btn btn-outline-danger">Cancel</a>
    </form>

</div>

{% endblock content %}

dealers/carsifydealers/templates/carsifydealers/login.html
{% extends 'carsifydealers/base.html' %}
{% load static %}
{% block title %}MyBlog|Login{% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5"><h2 class="mb-5">Login Page</h2></h3>
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}

        {% endif %}
    <form action="{% url 'userlogin' %}" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
            <i class="fas fa-lock"></i>
            <h3>{{fm.label_tag}}</h3>{{fm}}
            <span class="errorlist text-warning">{{fm.errors|striptags}}</span><br><br>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-outline-success">Login</button>
    </form>
            {% endblock content %}

dealers/carsifydealers/templates/carsifydealers/login2.html
{% load static %} 


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'carsifydealers/css/navbar.css' %}"
    />
    <link rel="stylesheet" href="{% static 'carsifydealers/css/login.css' %}" />
    <link
      rel="shortcut icon"
      href="{% static 'carsifydealers/images/favicon.png' %}"
      type="image/.png"
    />
    <title>Sign in & Sign up Form</title>
  </head>
  <body>
    {% if error %}
    <script>
      alert("password is incorrect");
    </script>
    {% endif %} 
    {% if Con %}
    <script>
      alert("all ready registed user");
    </script>
    {% endif %}
    {% if not_exist %}
    <script>
      alert("User do not exist");
    </script>
    {% endif %}

    <a href="{% url 'home' %}">
      <div class="logo">
        <img src="{% static 'carsifydealers/images/logo52.png' %}" alt="" srcset="" />
      </div>
    </a>
    <a href="{% url 'home' %}">
      <div class="logo2">
        <img src="{% static 'carsifydealers/images/logo62.png' %}" alt="" srcset="" />
      </div>
    </a>
    <div class="containers">
      <div class="forms-containers">
        <div class="signin-signup">
          
          <form
            method="post"
            action="{% url 'userlogin' %}"
            class="sign-in-form"
          >
            {% csrf_token %}
            <h2 class="title">Sign in</h2>
            {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}

        {% endif %}
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input name="username" type="text" placeholder="Email" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input
                name="password"
                type="password"
                placeholder="Password"
                id="PassField"
              />
            </div>
            <p class="show_pass">
              <input
                class="showpass"
                type="checkbox"
                onclick="showPass()"
              /><span class="showpass_label">Show Password</span>
            </p>
            <input type="submit" value="Login" class="btn solid" />
            <a href="#"
              >
              <div class="d-flex google-btn">
                <img class="google-icon mr-3" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/> Login With Google
              </div>
            </a>
            <label style="cursor: pointer; color: blue"
              >Forgot Password ?</label
            >
          </form>

          <form
            method="post"
            action="{% url 'usersignup' %}"
            class="sign-up-form"
            enctype="multipart/form-data"
            nonvalidate
          >
            {% csrf_token %}
            <h2 class="title">Sign up</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <!-- <input name="first_name" type="text" id="id_first_name" placeholder="Full Name" required/> -->
              <input type="text" name="first_name" class="form-control"placeholder="Name" required="" maxlength="150" id="id_first_name">
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input type="text" name="username" class="form-control" placeholder="Username" maxlength="150" autofocus="" required="" id="id_username">
            </div>
            <div class="input-field">
              <i class="fas fa-phone"></i>
              <!-- <input name="phonenumber" type="Number" id="id_phonenumber" placeholder="Mobile Number" required/> -->
              <input type="text" name="phonenumber" placeholder="Mobile" required="" id="id_phonenumber">
            </div>
            
            <!-- <div class="input-field">
              <i class="fas fa-map-marker"></i>
              <input type="text" placeholder="Address" />
            </div> -->
            <!-- <div class="input-field">
              <i class="fas fa-car"></i>
              <select>
                <option value="option one">option 1</option>
                <option value="option two">option 2</option>
                <option value="option three">option 3</option>
                <option value="option four">option 4</option>
              </select>
            </div> -->
            <!-- <div class="input-field">
              <i class="fas fa-car"></i>
              <select>
                <option value="option one">option 1</option>
                <option value="option two">option 2</option>
                
              </select>
            </div> -->
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <!-- <input name="password" id="id_password1"  type="password" placeholder="Password" required/> -->
              <input type="password" name="password1" placeholder="Password" class="form-control" required="" id="id_password1">
            </div>
            <div class="input-field">
                <i class="fas fa-lock"></i>
                <!-- <input name="password2" id="id_password2"  type="password" placeholder="Password" required/> -->
                <input type="password" name="password2" placeholder="Confirm Password" class="form-control" required="" id="id_password2">
              </div>
            
              <div class="input-field">
                <i class="fa-regular fa-image fas"></i>
                 <!-- <input name="password2" id="id_password2"  type="password" placeholder="Password" required/> -->
                <!--  <input type="file" name="gumasta" accept="image/*" required="" id="id_gumasta"> -->
                <input id="id_gumasta" name="gumasta"  type="file" required>
              </div>
              {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}

        {% endif %}
            <!-- <div class="input-field d-none " id="OTPField">
              <i class="fas fa-inbox"></i>
              <input name="otp" type="number" id="otp" max="9999" maxlength="4" placeholder="OTP" required/>
            </div> -->
            <button type="submit" class="btn btn-lg btn-outline-success">Submit</button>
            <!-- <input type="submit" value="Signup" class="btn solid" /> -->
            <!-- <input style="display: none; " type="file" id="image_one">
            <input style="display: none; " type="file" id="image_two">
            <input style="display: none; " type="file" id="image_three">
            <label for="">Upload Image<ul style="display: inline-block;">
              <i class="fa fa-plus" id="button_one" aria-hidden="true"></i>
              <i class="fa fa-plus" id="button_two" aria-hidden="true"></i>
              <i class="fa fa-plus" id="button_three" aria-hidden="true"></i>
            </ul>
          </label> -->
            <!-- <a href="#" class='google-sign-in'
              >
              <div class="d-flex google-btn">
                <img class="google-icon mr-3" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/> Login With Google
              </div>
            </a>
            <p class="text-decoration-none text-primary ms-auto d-none" id="resendOTP" onClick= "OTPSending();">Resend OTP</p>
            <button class="btn" type="button" onClick="OTPSending();" id="OTPBtn"> Send OTP</button>
            <button class="btn d-none" id="signupBtn" type="button" >Sign up</button> -->
          </form>
        </div>
      </div>

      <div class="panels-containers">
        <div class="panel left-panel">
          <div class="content">
            <h3>New here ?</h3>
            <p>
              If you're dealer looking to grow your business , Join us now !
            </p>
            <button class="btn transparent" id="sign-up-btn">Sign up</button>
          </div>
          <img
            src="{% static 'carsifydealers/images/one.png' %}"
            class="image"
            alt=""
          />
        </div>
        <div class="panel right-panel">
          <div class="content">
            <h3>One of us ?</h3>
            <p>Already a user , click below to sign in to your account</p>
            <button class="btn transparent" id="sign-in-btn">Sign in</button>
          </div>
          <img
            src="{% static 'carsifydealers/images/By_my_car-bro_(2).png' %}"
            class="image"
            alt=""
          />
        </div>
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
    {% comment %} <script src="{% static 'carsifydealers/js/otp.js' %}"></script> {% endcomment %}
    <script>
    $("#signupBtn").click(function(){
    var otp = $("#otp").val();
    $.ajax({
      method:"POST",
      url:"/checkOTP/",
      dataType:"json",
      data:{
        otp : otp,
        csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success:function(res){
          if(res.data == 1){
            $.ajax({
              url:"/signup/",
              dataType:"json",
              method:"POST",
              data:{
                'name': $("#name").val(),
                'email' : $("#email").val(),
                'number': $("#number").val(),
                'password' : $("#password").val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
              },
            })
            window.location.reload();
          }
          if(res.data == 0){
          alert("Invalid OTP");}
      }
    })
  });

  function CheckFields(){
    var name = $("#name").val();
    var email = $("#email").val();
    var number = $("#number").val();
    var password = $("#password").val();
    if(name == "" || email == "" || number == "" || password.trim() == ""){
      console.log(name," ",email," ",number," ",password);
      return false;
    }
    return true;
}  

var password = document.querySelector("#password");
password.on("keyup",function(e){
  if(e.keyCode == 13){
    $("#OTPBtn").click();
  }
});

function OTPSending(){
  var email = document.querySelector("#email").value;
  if(CheckFields()){
    $.ajax({
      url: "/mailOTP/",
      type: "POST",
      dataType: "json",
      data: {
        email: email
      },
      success: function (response) {
        if(response.exist == 1){
          alert("Email Already Registered!");
        }
        else{
        console.log(response.data)
        $("#resendOTP").removeClass("d-none");
        $("#OTPField").removeClass("d-none");
        $("#OTPBtn").addClass("d-none");
        $("#signupBtn").removeClass("d-none");
        $(".google-sign-in").addClass("d-none");}
      }
    });
  }
};
      var logo = document.querySelector(".logo");
      var btn = document.querySelector("#sign-up-btn");
      var logo2 = document.querySelector(".logo2");
      var btn2 = document.querySelector("#sign-in-btn");

      btn.addEventListener("click", function () {
        logo.style.display = "none";
        logo2.style.display = "block";
      });

      btn2.addEventListener("click", function () {
        logo2.style.display = "none";
        logo.style.display = "block";
      });

      function showPass() {
        var x = document.getElementById("PassField");
        if (x.type === "password") {
          x.type = "text";
        } else {
          x.type = "password";
        }
      }
      </script>
    <script src="{% static 'carsifydealers/js/app.js' %}"></script>
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>